### ISSUE TITLE
명령어 옵션에 토큰을 적으면 노출될 수 있음

### ISSUE THREAD

**Issue by enbraining** [xolving/Gitty-bot#1]
<img width="188" alt="Screenshot 2024-01-28 at 10 59 08 PM" src="https://github.com/xolving/Gitty-bot/assets/119437754/180d9053-9b6e-4adf-986e-11a34253b5c2">
명령어를 클릭하면 입력한 옵션이 노출됨

**Comment by imnyang** [comment]
use .env

**Comment by imnyang** [comment]
or Ephemeral message

**Comment by enbraining** [comment]
> use .env

처음에는 .env를 사용했지만 여러 서버에서 지원할 목적으로 SetDefault가 생긴거라서 어려울 것 같아요
